
```{r source, include = FALSE}
# Source analysis script
source(here::here("outputs", "technical_report", "scripts", "analysis_script.R"))

```

# Overview

The objective of this scoping review is to examine the extent of empirical research evidence on the four-day school week (4DSW) at primary and secondary schools in the United States. Compared to traditional systematic reviews estimating the effects of interventions, scoping reviews explore the breadth of the literature on a topic, identify the types of available evidence, and chart and summarize this evidence (Peters et al., 2020). Scoping reviews are particularly useful for examining evidence on emerging topics to inform specific questions that can be valuably answered in future evidence syntheses. Consequently, a scoping review can provide useful insights about the nature and state of available research evidence in the 4DSW literature.

## Abstract

The four-day school week (4DSW) is an alternative schedule gaining popularity among K-12 schools in the United States, with a resultant growing body of empirical research. This scoping review examined the extent and types of published empirical research evidence on the 4DSW. As of `r our_search_date`, we located `r nrow(raw_df)` empirical research studies on the 4DSW in U.S. K-12 schools. The majority of studies provided evidence on the `r evidence_summary$Category[1]` of 4DSWs (n = `r evidence_summary$N[1]`; `r round(evidence_summary$Percentage[1], 0)`%), examined 4DSWs in `r community_summary$Category[1]` communities (n = `r community_summary$N[1]`; `r round(community_summary$Percentage[1], 0)`%), and are published in `r publication_summary$Category[1]` (n = `r publication_summary$N[1]`; `r round(publication_summary$N[1]/nrow(raw_df)*100, 0)`%). We created an online interactive database for stakeholders to explore the diverse types of available evidence for studies most relevant to their specific contexts and informational needs. 
