# Background

The four-day school week (4DSW) is an alternative school schedule in which students only attend school four days per week, with schools attempting to compensate for lost instructional time by increasing the school day or school calendar year. Historically, school districts have switched to the 4DSW primarily for anticipated cost savings and attendance issues commonly faced by schools located in rural communities (Thompson et al., 2021). Since the onset of the COVID-19 pandemic, districts are increasingly considering the 4DSW as a non-pecuniary benefit for teachers and staff (Camp et al., 2024).. This alternative school schedule is gaining popularity among K-12 schools in the United States, as more than 2,100 schools in nearly 900 districts across 26 states have adopted a 4DSW (Morton et al., 2024). 

As a result of interest in the 4DSW across the United States, a growing body of empirical research aims to provide stakeholders information on its effects and implementability. For example, numerous studies have examined whether the 4DSW achieves its stated aims on cost-savings (Morton, 2021; Thompson, 2021), student attendance (Morton, 2023; Thompson et al., 2022), and teacher recruitment and retention (Camp et al., 2024; Maiden et al., 2020). In addition, educational stakeholders are concerned about potential unintended negative and inequitable impacts on student achievement (Morton et al., 2024; Thompson et al., 2023; Thompson & Ward, 2022), health (Israel et al., 2020; Tomayko et al., 2020, 2021), and societal well-being (Fischer & Argyle, 2018). Stakeholders also want to learn about the experience of implementing the 4DSW, such as satisfaction with the schedule change and district services available on the fifth “off day” (Kilburn et al., 2021). Given mixed and heterogeneous findings across 4DSW studies, stakeholders particularly want to use research evidence from studies most relevant to their specific educational contexts and informational needs. However, to date, no evidence synthesis has systematically identified and characterized empirical research studies on the 4DSW.

The objective of this scoping review was therefore to examine the extent and types of published empirical research evidence available on the 4DSW at U.S. K-12 schools. Scoping reviews aim to explore and characterize the breadth of the published literature on a research topic (Peters et al., 2020; Tricco et al., 2018). Scoping reviews are particularly useful as a preliminary exercise in an emerging research area when it is still unclear whether more specific questions can be valuably addressed in future systematic reviews (Anderson et al., 2008). Consequently, this scoping review summarizes the types of empirical research evidence available for education stakeholders, assesses whether sufficient evidence exists for subsequent systematic reviews, and identifies existing gaps in the literature to inform future primary research.
