
```{r source, include = FALSE}
# Source analysis script
source(here::here("outputs", "technical_report", "scripts", "analysis_script.R"))

```

# Methods

We designed this study using the JBI Manual for Evidence Synthesis (Peters et al., 2020) and prospectively registered the review on the Open Science Framework (https://osf.io/xcthk). We drafted this manuscript using the Preferred Reporting Items for Systematic reviews and Meta-Analyses (PRISMA) extension for literature searches (Rethlefsen et al., 2021) and the PRISMA extension for scoping reviews (Tricco et al., 2018). 

## Eligibility Criteria

We included empirical studies examining 4DSWs at K-12 schools. We excluded studies focused on other alternative school schedules (e.g., extending the school year) that did not involve reducing traditional five-day school weeks to 4DSWs. Based on the interests of our research institute advisory board and stakeholders, we excluded studies in pre-school, postsecondary school, and countries other than the United States. The population of interest was any stakeholder considering the shift to a 4DSW. We included all research designs that involved the analysis of empirical data or simulated empirical data. We excluded conceptual papers, opinion articles, narrative literature reviews, and non-research sources (e.g., news). We included grey literature unless we could not obtain the full-text. Due to limitations in resources and language proficiency, we excluded studies published in languages other than English.

## Information Sources

We searched for eligible studies from May 2023 to `r our_search_date` using the following electronic databases (with search platforms in parentheses): PubMed (National Library of Medicine), ProQuest Dissertations & Theses A&I (ProQuest), and Social Science Premium Collection (ProQuest). The Social Science Premium Collection includes the Criminology Collection, Education Collection (which includes Education Resources Information Center, or “ERIC”), International Bibliography of the Social Sciences, Library & Information Science Collection, Linguistics Collection, Politics Collection, Social Science Database, and Sociology Collection. To identify any further potentially eligible citations, we searched reference lists of included studies and citing references using *citationchaser* (Haddaway et al., 2022). We additionally hand-searched several key journals: *Economics of Education Review, Education Finance and Policy, Journal of Education and Training Studies, Journal of School Health,* and *Rural Educator*. We also looked for grey literature using Google Scholar. Although we did not contact authors nor search specific websites, we did add citations identified serendipitously (e.g., through social media).

## Search Strategy

A copy of the full search strategy is available on the Open Science Framework (https://osf.io/ryva8/). We developed the search strategy using the Peer Review of Electronic Search Strategies (PRESS) Guideline (McGowan et al., 2016) and terms common in studies identified in a preliminary scan of the literature on Google Scholar. The search strategy did not involve the use of any published search filters. We uploaded the citations into a web-based systematic review data management software (DistillerSR) and used its “Duplicate Detection” function to search for duplicates prior to screening.

## Selection Process of Sources of Evidence

A copy of the selection process codebook is available on the Open Science Framework (https://osf.io/ryva8/). Two review authors independently screened titles and abstracts of each citation for potentially eligible studies. We retrieved full-texts for each citation deemed potentially eligible by at least one reviewer. Two review authors independently assessed each full-text for eligibility, recording reasons for excluding citations. Reviewers discussed initial disagreements of full-text eligibility decisions, meeting with a third reviewer as needed for unresolved disagreements. We used standardized forms in DistillerSR and did not blind review authors to journal titles, study authors, and authors’ institutions. 

## Data Charting Process and Items

One PhD-level reviewer (SG), and either another graduate-level reviewer (KSF) or two undergraduate reviewers (a combination of BC, SH, and SM), independently collected data from each eligible article using DistillerSR. Reviewers resolved any disagreements through discussion, meeting with a third reviewer as needed for unresolved disagreements. We developed our data collection form through an iterative process—continually updating the items as data collection progressed and revisiting studies when new items were added to the form (Peters et al., 2020; Tricco et al., 2018). The form began with bibliographic items for author name, publication year, publication type (journal article, preprint, report, or student dissertation/thesis), and publisher (journal, preprint server, organization, or university). For student manuscripts, we collected information on degree level (doctoral, masters, or undergraduate) and discipline (economics, education, music, psychology, or sociology). The form then included items characterizing the source of evidence: i.e., years from which study data were collected, community types (rural, suburban, urban) and states in which the study took place, grade and school levels, student race/ethnicity, and any activities on the fifth “off day” officially offered by schools or districts. Because scoping reviews aim to characterize the extent and nature of existing evidence regardless of methodological quality or risk of bias, we did not critically appraise the included sources of evidence (Tricco et al., 2018).

The data collection form concluded with items about the types of empirical evidence provided by included studies. Based on the GRADE Evidence-to-Decision framework for structuring policy and practice decision-making (Alonso-Coello et al., 2016), we assessed six types of empirical evidence: acceptability (extent to which the 4DSW is acceptable to specific stakeholder groups), effectiveness (impact of the 4DSW on student, school, and community outcomes), equity (degree to which the 4DSW has differential impacts by population and setting), feasibility (how the 4DSW was implemented), priority (focused on examining growth of schools, districts, or states adopting the 4DSW), and resource use (costs and resource implications of 4DSW adoption).


## Synthesis of Results

We narratively and visually summarized the study search and selection process via the number of records screened, assessed for eligibility, and included in our scoping review (Page et al., 2021; Tricco et al., 2018). We analyzed and summarized characteristics of the empirical research evidence through descriptive statistics. We present results through narrative and tabular summaries.
