
```{r source, include = FALSE}
# Source analysis script
source(here::here("outputs", "technical_report", "scripts", "analysis_script.R"))

# Function to format numbers with thousand-comma
format_thousands <- function(x) {
  format(x, big.mark = ",", scientific = FALSE, trim = TRUE)
}

# Function to pull Category name, N, and Percentage from specific Category name (when ignoring majority arrange)
pull_summary_value <- function(df, category_filter, column) {
  value <- df %>%
    filter(Category == category_filter) %>%
    pull({{ column }})  # Extract the selected column

  # Convert column name to character
  column_name <- deparse(substitute(column))  

  # Only round Percentage values
  if (column_name == "Percentage") {
    return(round(value, 0))
  } else {
    return(value)  # Leave other values unchanged
  }
}

```

# Results

Of `r format_thousands(number_search_results)` unique citations, we excluded `r format_thousands(number_dropped)` citations during title and abstract screening. Of the `r format_thousands(number_kept)` remaining citations we could locate for full-text eligibility assessment, we excluded `r format_thousands(number_ineligible)` citations. We included the remaining `r format_thousands(number_eligible)` studies (reported in `r nrow(number_eligible_reports)` manuscripts) in our scoping review (see [Figure 1](#fig-flow-diagram)).

## Characteristics of Sources of Evidence

We provide a summary of characteristics of sources of evidence in [Table 1](#tbl1-study-char). Included studies were published from `r publication_year_summary$Min` to `r publication_year_summary$Max` (median of `r publication_year_summary$Median`). Of the `r format_thousands(number_eligible)` studies, most (n = `r publication_summary$N[1]`; `r round(publication_summary$N[1]/nrow(raw_df)*100, 0)`%) are published in `r publication_summary$Category[1]`: `r grey_lit_summary$N[1]` (`r round(grey_lit_summary$Percentage[1], 0)`%) as a `r grey_lit_summary$Category[1]`, `r grey_lit_summary$N[2]` (`r round(grey_lit_summary$Percentage[2], 0)`%) as a `r grey_lit_summary$Category[1]`, and `r grey_lit_summary$N[3]` (`r round(grey_lit_summary$Percentage[3], 0)`%) as a `r grey_lit_summary$Category[3]`. Only `r journal_summary$N[1]` studies (`r round(journal_summary$Percentage[1], 0)`%) had a peer-reviewed journal article as the final version of record. Of the `r grey_lit_summary$N[1]` `r grey_lit_summary$Category[1]` article types, `r student_type_summary$N[1]` (`r round(student_type_summary$Percentage[1], 0)`% of student manuscripts) were a `r student_type_summary$Category[1]`, `r student_type_summary$N[2]` (`r round(student_type_summary$Percentage[2], 0)`%) were a `r student_type_summary$Category[2]`, and `r student_type_summary$N[3]` (`r round(student_type_summary$Percentage[3], 0)`%) were an `r student_type_summary$Category[3]`. Most students completed dissertations and theses in partial fulfillment of degrees in `r student_disc_summary$Category[1]` (n = `r student_disc_summary$N[1]`; `r round(student_disc_summary$Percentage[1], 0)`%), followed by `r student_disc_summary$Category[2]` (n = `r student_disc_summary$N[2]`; `r round(student_disc_summary$Percentage[2], 0)`%), `r student_disc_summary$Category[3]` (n = `r student_disc_summary$N[3]`; `r round(student_disc_summary$Percentage[3], 0)`%), `r student_disc_summary$Category[4]` (n = `r student_disc_summary$N[4]`; `r round(student_disc_summary$Percentage[4], 0)`%), and `r student_disc_summary$Category[5]` (n = `r student_disc_summary$N[5]`; `r round(student_disc_summary$Percentage[5], 0)`%).

Studies collected and analyzed data from `r summary_data_years$Min` to `r summary_data_years$Max` (median of `r summary_data_years$Median`). Studies predominantly included data from `r community_summary$Category[1]` communities in their sample (n = `r community_summary$N[1]`; `r round(community_summary$Percentage[1], 0)`%), though numerous studies also included data from `r community_summary$Category[2]` (n = `r community_summary$N[2]`; `r round(community_summary$Percentage[2], 0)`%) and `r community_summary$Category[3]` communities in their samples (n = `r community_summary$N[3]`; `r round(community_summary$Percentage[3], 0)`%); `r community_summary$N[4]` studies (`r round(community_summary$Percentage[4], 0)`%) did not report information on community type. Studies included data from `r nrow(filter(state_summary, Category != "unknown"))` states — most predominantly from `r state_summary$Category[1]` (n = `r state_summary$N[1]`; `r round(state_summary$Percentage[1], 0)`%), `r state_summary$Category[2]` (n = `r state_summary$N[2]`; `r round(state_summary$Percentage[2], 0)`%), `r state_summary$Category[3]` (n = `r state_summary$N[3]`; `r round(state_summary$Percentage[3], 0)`%), `r state_summary$Category[4]` (n = `r state_summary$N[4]`; `r round(state_summary$Percentage[4], 0)`%), `r state_summary$Category[5]` (n = `r state_summary$N[5]`; `r round(state_summary$Percentage[5], 0)`%), and `r state_summary$Category[6]` (n = `r state_summary$N[6]`; `r round(state_summary$Percentage[6], 0)`%). The number of studies providing data from `r pull_summary_value(school_summary, "elementary", Category)` (n = `r pull_summary_value(school_summary, "elementary", N)`; `r pull_summary_value(school_summary, "elementary", Percentage)`%), `r pull_summary_value(school_summary, "middle", Category)` (n = `r pull_summary_value(school_summary, "middle", N)`; `r pull_summary_value(school_summary, "middle", Percentage)`%), and `r pull_summary_value(school_summary, "high", Category)` (n = `r pull_summary_value(school_summary, "high", N)`; `r pull_summary_value(school_summary, "high", Percentage)`%) schools was fairly evenly distributed across levels, *with data representing all grades (except kindergarten) included in at least half the studies*. Most studies did not provide information on student race/ethnicity (n = `r pull_summary_value(race_summary, "not reported", N)`; `r pull_summary_value(race_summary, "not reported", Percentage)`%) nor activities on the fifth “off day” officially offered by schools or districts (n = `r pull_summary_value(fifthday_summary, "not reported", N)`; `r pull_summary_value(fifthday_summary, "not reported", Percentage)`%).

## Types of Empirical Research Evidence

We provide a summary of types of empirical research evidence in [Table 2](#tbl2-study-evidence). Of the `r format_thousands(number_eligible)` included studies, most reported evidence on 4DSW `r evidence_summary$Category[1]` (n = `r evidence_summary$N[1]`; `r round(evidence_summary$Percentage[1], 0)`%). Among these `r pull_summary_value(evidence_summary, "effectiveness", N)` studies, `r nrow(filter(approach_summary, Category != "unknown" | Category != "not reported"))` different methodological and statistical approaches were used: `r approach_summary$N[1]` studies used `r approach_summary$Category[1]` (`r round(approach_summary$Percentage[1], 0)`% of effectiveness studies), `r approach_summary$N[2]` studies (`r round(approach_summary$Percentage[2], 0)`%) used `r approach_summary$Category[2]`, `r approach_summary$N[3]` (`r round(approach_summary$Percentage[3], 0)`%) studies used a `r approach_summary$Category[3]` design, `r approach_summary$N[4]` studies (`r round(approach_summary$Percentage[4], 0)`%) used a `r approach_summary$Category[4]` design, `r approach_summary$N[5]` studies (`r round(approach_summary$Percentage[5], 0)`%) used a `r approach_summary$Category[5]` design, `r approach_summary$N[6]` studies (`r round(approach_summary$Percentage[6], 0)`%) used a `r approach_summary$Category[6]`, and `r approach_summary$N[7]` studies (`r round(approach_summary$Percentage[7], 0)`%) used a `r approach_summary$Category[7]` design. These `r pull_summary_value(evidence_summary, "effectiveness", N)` studies provided outcome data across `r nrow(filter(outcome_summary, Category != "unknown" | Category != "not reported"))` domains: `r outcome_summary$N[1]` studies (`r round(outcome_summary$Percentage[1], 0)`% of effectiveness studies) reported on `r outcome_summary$Category[1]`, `r outcome_summary$N[2]` (`r round(outcome_summary$Percentage[2], 0)`%) on `r outcome_summary$Category[2]`, `r outcome_summary$N[3]` (`r round(outcome_summary$Percentage[3], 0)`%) on `r outcome_summary$Category[3]`, `r outcome_summary$N[4]` (`r round(outcome_summary$Percentage[4], 0)`%) on `r outcome_summary$Category[4]`, `r outcome_summary$N[5]` (`r round(outcome_summary$Percentage[5], 0)`%) on `r outcome_summary$Category[5]`, `r outcome_summary$N[6]` (`r round(outcome_summary$Percentage[6], 0)`%) on `r outcome_summary$Category[6]`, `r outcome_summary$N[7]` (`r round(outcome_summary$Percentage[7], 0)`%) on `r outcome_summary$Category[7]`, `r outcome_summary$N[8]` (`r round(outcome_summary$Percentage[8], 0)`%) on `r outcome_summary$Category[8]`, and `r outcome_summary$N[9]` (`r round(outcome_summary$Percentage[9], 0)`%) on `r outcome_summary$Category[9]`. Most effectiveness studies (n = `r pull_summary_value(evidence_summary, "equity", N)`; `r pull_summary_value(evidence_summary, "equity", Percentage)`% of effectiveness studies) also reported evidence on *equity* of 4DSW effects according to `r nrow(filter(equity_summary, Category != "unknown" | Category != "not reported"))` domains: `r equity_summary$N[1]` (`r round(equity_summary$Percentage[1], 0)`% of equitability studies) on `r equity_summary$Category[1]`, `r equity_summary$N[2]` (`r round(equity_summary$Percentage[2], 0)`%) on `r equity_summary$Category[2]`, `r equity_summary$N[3]` (`r round(equity_summary$Percentage[3], 0)`%) on `r equity_summary$Category[3]`, `r equity_summary$N[4]` (`r round(equity_summary$Percentage[4], 0)`%) on `r equity_summary$Category[4]`, `r equity_summary$N[5]` (`r round(equity_summary$Percentage[5], 0)`%) on `r equity_summary$Category[5]`, `r equity_summary$N[6]` (`r round(equity_summary$Percentage[6], 0)`%) on `r equity_summary$Category[6]`, `r equity_summary$N[7]` (`r round(equity_summary$Percentage[7], 0)`%) on `r equity_summary$Category[7]`, `r equity_summary$N[8]` (`r round(equity_summary$Percentage[8], 0)`%) on `r equity_summary$Category[8]`, and `r equity_summary$N[9]` (`r round(equity_summary$Percentage[9], 0)`%) on `r equity_summary$Category[9]`.

Of the `r implementability_summary$Denominator[1]` studies (`r round(implementability_summary$Denominator[1] / number_eligible * 100, 0)`%) that reported one type of evidence on the implementability of the 4DSW, most (n = `r implementability_summary$N[1]`; `r round(implementability_summary$Percentage[1], 0)`% of studies with implementability data) reported evidence on `r implementability_summary$Category[1]`. These `r implementability_summary$N[1]` studies examined satisfaction with the 4DSW among `r stakeholder_summary$Category[1]` (n = `r stakeholder_summary$N[1]`; `r round(stakeholder_summary$Percentage[1], 0)`%), `r stakeholder_summary$Category[2]` (n = `r stakeholder_summary$N[2]`; `r round(stakeholder_summary$Percentage[2], 0)`%), `r stakeholder_summary$Category[3]` (n = `r stakeholder_summary$N[3]`; `r round(stakeholder_summary$Percentage[3], 0)`%), `r stakeholder_summary$Category[4]` (n = `r stakeholder_summary$N[4]`; `r round(stakeholder_summary$Percentage[4], 0)`%), `r stakeholder_summary$Category[5]` (n = `r stakeholder_summary$N[5]`; `r round(stakeholder_summary$Percentage[5], 0)`%), `r stakeholder_summary$Category[6]` (n = `r stakeholder_summary$N[6]`; `r round(stakeholder_summary$Percentage[6], 0)`%), `r stakeholder_summary$Category[7]` (n = `r stakeholder_summary$N[7]`; `r round(stakeholder_summary$Percentage[7], 0)`%), `r stakeholder_summary$Category[8]` (n = `r stakeholder_summary$N[8]`; `r round(stakeholder_summary$Percentage[8], 0)`%), `r stakeholder_summary$Category[9]` (n = `r stakeholder_summary$N[9]`; `r round(stakeholder_summary$Percentage[9], 0)`%), `r stakeholder_summary$Category[10]` (n = `r stakeholder_summary$N[10]`; `r round(stakeholder_summary$Percentage[10], 0)`%), `r stakeholder_summary$Category[11]` (n = `r stakeholder_summary$N[11]`; `r round(stakeholder_summary$Percentage[11], 0)`%), and `r stakeholder_summary$Category[12]` (n = `r stakeholder_summary$N[12]`; `r round(stakeholder_summary$Percentage[12], 0)`%). In addition, `r pull_summary_value(implementability_summary, "feasibility", N)` studies (`r pull_summary_value(implementability_summary, "feasibility", Percentage)`% of studies with implementability data) reported evidence on feasibility of implementing the 4DSW, and `r pull_summary_value(implementability_summary, "resource", N)` (`r pull_summary_value(implementability_summary, "resource", Percentage)`%) reported evidence on resource use associated with switching to a 4DSW. Lastly, only `r pull_summary_value(evidence_summary, "priority", N)` studies (`r pull_summary_value(evidence_summary, "priority", Percentage)`% of all studies) reported evidence on 4DSW as a policy priority through an explicit empirical focus on the growth of schools, districts, or states adopting the 4DSW. 

