
```{r source, include = FALSE}
# Source analysis script
source(here::here("outputs", "technical_report", "scripts", "analysis_script.R"))

# Function to format numbers with thousand-comma
format_thousands <- function(x) {
  format(x, big.mark = ",", scientific = FALSE, trim = TRUE)
}

```

# Discussion

Our scoping review identified `r format_thousands(number_eligible)` studies published from`r publication_year_summary$Min` to `r publication_year_summary$Max`. Our findings indicate that empirical research evidence exists on the acceptability, effectiveness, equity, feasibility, priority, and resource use associated with 4DSW adoption across a range of states. Most studies reported evidence on 4DSW effects, though outcomes measured and rigor of the method used to assess effectiveness (and thus potential credibility of the evidence) vary considerably across these studies. In addition, more than half the studies examined at least one aspect of 4DSW implementability (i.e., acceptability, feasibility, or resource use). Strikingly, the vast majority of existing empirical research evidence is available only in the grey literature. To make this body of evidence more readily available to interested stakeholders, we created an [online interactive bibliographic database](https://hedcoinstitute.uoregon.edu/dashboards/four-day-school-week-research-database) that provides links to and information about each included study providing empirical research evidence on 4DSWs in the United States. Stakeholders can use this open access database to explore the diverse types of evidence available and find the studies most relevant to their specific contexts and sufficiently reliable for their evidence-informed decision-making needs.

Given continued stakeholder interest in the 4DSW as an alternative school schedule, and the growing body of research on the 4DSW documented in this scoping review, there is clearly a need for future systematic reviews synthesizing the findings of empirical studies on the 4DSW. These reviews might assess the quality and rigor of available studies; estimate average and differential impacts on student, school, and community outcomes; and examine implementability of the 4DSW. That said, this current scoping review has already identified several key gaps in the existing evidence base that should be addressed in future primary research. For instance, although evidence from non-rural communities, on marginalized populations, and collected after the onset of the COVID-19 pandemic does exist, the literature predominantly represents rural communities, is based on data collected prior to the pandemic, and does not examine equitability implications. In addition, future primary research should investigate and report information on student demographics, differential findings by various gradients of societal advantage, and activities offered on the fifth day. These additional primary studies and future systematic reviews can provide a range of education stakeholders with valuable evidence that can inform their decision-making around the tradeoffs associated with a shift to a 4DSW. 
