# References

Alonso-Coello, P., Schünemann, H. J., Moberg, J., Brignardello-Petersen, R., Akl, E. A., Davoli, M., Treweek, S., Mustafa, R. A., Rada, G., Rosenbaum, S., Morelli, A., Guyatt, G. H., & Oxman, A. D. (2016). GRADE Evidence to Decision (EtD) frameworks: A systematic and transparent approach to making well informed healthcare choices. 1: Introduction. BMJ, 353, i2016. https://doi.org/10.1136/bmj.i2016

Anderson, S., Allen, P., Peckham, S., & Goodwin, N. (2008). Asking the right questions: Scoping studies in the commissioning of research on the organisation and delivery of health services. Health Research Policy and Systems, 6(1), 7. https://doi.org/10.1186/1478-4505-6-7

Camp, A., Wilson, T., Liu, Y., Anglum, J. C., Manion, A., & Nguyen, T. (2024). Teacher retention and the four-day school week in Missouri. Policy Research in Missouri Education Center at Saint Louis University.

Fischer, S., & Argyle, D. (2018). Juvenile crime and the four-day school week. Economics of Education Review, 64, 31–39. https://doi.org/10.1016/j.econedurev.2018.03.010

Israel, W., Mulitauopele, C., Ma, M., Levinson, A. H., Cikara, L., & Brooks-Russell, A. (2020). Adolescent health behaviors in schools with 4- versus 5-day school weeks. Journal of School Health, 90(10), 794–801. https://doi.org/10.1111/josh.12941

Kilburn, M. R., Phillips, A., Gomez, C. J., Mariano, L. T., Doss, C. J., Troxel, W. M., Morton, E., & Estes, K. (2021). Does four equal five? Implementation and outcomes of the four-day school week. RR-A373-1. In RAND Corporation. RAND Corporation. https://doi.org/10.7249/RR-A373-1

Maiden, J., Crowson, H. M., & Byerly, C. (2020). The influence of the adoption of a school district four day instructional week on teacher retention. Journal of Education Finance, 46(2), 117–139.

McGowan, J., Sampson, M., Salzwedel, D. M., Cogo, E., Foerster, V., & Lefebvre, C. (2016). PRESS Peer Review of Electronic Search Strategies: 2015 Guideline Statement. Journal of Clinical Epidemiology, 75, 40–46. https://doi.org/10.1016/j.jclinepi.2016.01.021

Morton, E. (2021). Effects of four-day school weeks on school finance and achievement: Evidence from Oklahoma. Educational Researcher, 50(1), 30–40. https://doi.org/10.3102/0013189X20948023

Morton, E. (2023). Effects of 4-day school weeks on older adolescents: Examining impacts of the schedule on academic achievement, attendance, and behavior in high school. Educational Evaluation and Policy Analysis, 45(1), 52–78. https://doi.org/10.3102/01623737221097420

Morton, E., Thompson, P. N., & Kuhfeld, M. (2024). A multi-state, student-level analysis of the effects of the four-day school week on student achievement and growth. Economics of Education Review, 100, 102524. https://doi.org/10.1016/j.econedurev.2024.102524


Page, M. J., McKenzie, J. E., Bossuyt, P. M., Boutron, I., Hoffmann, T. C., Mulrow, C. D., Shamseer, L., Tetzlaff, J. M., Akl, E. A., Brennan, S. E., Chou, R., Glanville, J., Grimshaw, J. M., Hróbjartsson, A., Lalu, M. M., Li, T., Loder, E. W., 

Mayo-Wilson, E., McDonald, S., … Moher, D. (2021). The PRISMA 2020 Statement: An updated guideline for reporting systematic reviews. BMJ, 372, n71. https://doi.org/10.1136/bmj.n71

Peters, M., Godfrey, C., McInerney, P., Munn, Z., Tricco, A. C., & Khalil, H. (2020). Chapter 11: Scoping Reviews. In E. Aromataris & Z. Munn (Eds.), JBI Manual for Evidence Synthesis. JBI.

Rethlefsen, M. L., Kirtley, S., Waffenschmidt, S., Ayala, A. P., Moher, D., Page, M. J., Koffel, J. B., Blunt, H., Brigham, T., Chang, S., Clark, J., Conway, A., Couban, R., de Kock, S., Farrah, K., Fehrmann, P., Foster, M., Fowler, S. A., Glanville, J., … PRISMA-S Group. (2021). PRISMA-S: An extension to the PRISMA Statement for reporting literature searches in systematic reviews. Systematic Reviews, 10(1), 39. https://doi.org/10.1186/s13643-020-01542-z

Thompson, P. N. (2021). Does a day lost equal dollars saved? The effects of four-day school weeks on school district expenditures. National Tax Journal, 74(1), 147–183. https://doi.org/10.1086/712916

Thompson, P. N., Gunter, K., Schuna, Jr., John M., & Tomayko, E. J. (2021). Are all four-day school weeks created equal? A national assessment of four-day school week policy adoption and implementation. Education Finance and Policy, 16(4), 558–583. https://doi.org/10.1162/edfp_a_00316

Thompson, P. N., Tomayko, E. J., Gunter, K. B., & Schuna, J. (2022). Impacts of the four-day school week on high school achievement and educational engagement. Education Economics, 30(5), 527–539. https://doi.org/10.1080/09645292.2021.2006610

Thompson, P. N., Tomayko, E. J., Gunter, K. B., Schuna, J., & McClelland, M. (2023). Impacts of the four-day school week on early elementary achievement. Early Childhood Research Quarterly, 63, 264–277. https://doi.org/10.1016/j.ecresq.2022.12.009

Thompson, P. N., & Ward, J. (2022). Only a matter of time? The role of time in school on four-day school week achievement impacts. Economics of Education Review, 86, 102198. https://doi.org/10.1016/j.econedurev.2021.102198

Tomayko, E. J., Gunter, K. B., Schuna, J. M., & Thompson, P. N. (2020). Effects of four-day school weeks on physical education exposure and childhood obesity. Journal of Physical Activity and Health, 17(9), 902–906. https://doi.org/10.1123/jpah.2019-0648

Tomayko, E. J., Thompson, P. N., Smith, M. C., Gunter, K. B., & Schuna Jr., J. M. (2021). Impact of reduced school exposure on adolescent health behaviors and food security: Evidence from 4-day school weeks. Journal of School Health, 91(12), 1055–1063. https://doi.org/10.1111/josh.13095

Tricco, A. C., Lillie, E., Zarin, W., O’Brien, K. K., Colquhoun, H., Levac, D., Moher, D., Peters, M. D. J., Horsley, T., Weeks, L., Hempel, S., Akl, E. A., Chang, C., McGowan, J., Stewart, L., Hartling, L., Aldcroft, A., Wilson, M. G., Garritty, C., … Straus, S. E. (2018). PRISMA Extension for Scoping Reviews (PRISMA-ScR): Checklist and Explanation. Annals of Internal Medicine, 169(7), 467–473. https://doi.org/10.7326/M18-0850

