
```{r setup, include = FALSE}
library(gt)
# Source analysis script
source(here::here("outputs", "technical_report", "scripts", "analysis_script.R"))

```

# Appendices

## Appendix 1. List of Studies Excluded at Full-Text Eligibility Assessment

```{r a1-tbl, results = 'asis', echo = FALSE}
# Create gt table and format
a1_table <- a1_info %>% 
  gt()  %>% 
  cols_label(citation_cleaned = "Excluded Review", 
             study_exclude_reason = "Reason for Exclusion") %>% 
  tab_style(style = list(cell_borders(sides = "all", color = "black", weight = px(1))),
            locations = cells_body(columns = everything())) %>% 
  tab_style(style = list(cell_borders(sides = "all", color = "black", weight = px(1)),
                         cell_text(weight = "bold")),
            locations = cells_column_labels()) %>% 
  tab_options(column_labels.border.top.color = "black",
              column_labels.border.bottom.color = "black",
              table_body.border.bottom.color = "black",
              table.border.top.color = "white",
              heading.border.bottom.color = "black",
              table_body.hlines.color = "white",
              table.border.bottom.color = "white",
              table.font.names = "Times New Roman") %>% 
  tab_style(style = list(cell_text(align = "center")),
            locations = cells_title(groups = "title")) %>% 
  cols_width(citation_cleaned ~ pct(70), 
             study_exclude_reason ~ pct(30))

print(a1_table)

```

## Appendix 2. List of Studies Awaiting Classification

```{r a2-tbl, results = 'asis', echo = FALSE}
# Create formatted gt table
a2_table <- a2_info %>% 
  gt()  %>% 
  cols_label(citation_cleaned = "Study", 
             reason = "Reason") %>% 
  tab_style(style = list(cell_borders(sides = "all", color = "black", weight = px(1))),
            locations = cells_body(columns = everything())) %>% 
  tab_style(style = list(cell_borders(sides = "all", color = "black", weight = px(1)),
                         cell_text(weight = "bold")),
            locations = cells_column_labels()) %>% 
  tab_options(column_labels.border.top.color = "black",
              column_labels.border.bottom.color = "black",
              table_body.border.bottom.color = "black",
              table.border.top.color = "white",
              heading.border.bottom.color = "black",
              table_body.hlines.color = "white",
              table.border.bottom.color = "white",
              table.font.names = "Times New Roman") %>% 
  tab_style(style = list(cell_text(align = "center")),
            locations = cells_title(groups = "title")) %>% 
  cols_width(citation_cleaned ~ pct(78), 
             reason ~ pct(22))

print(a2_table)
```


## Appendix 3. Characteristics of Included Studies

```{r a3-maptable, results ='asis', echo = FALSE}
#create gt table for each for each review
list_gt <- lapply(split(combined_a3, combined_a3$source), function(x) {
  gt(x) %>% 
    cols_hide("source") %>% 
    cols_label(variable = "",
               value = "") %>% 
    tab_style(style = list(cell_text(weight = "bold")),
            locations = cells_body(columns = "variable")) %>% 
    tab_options(table.font.names = "Times New Roman",
                table.width = "100%") %>% 
    cols_width(variable ~ pct(20),
               value ~ pct(80)) %>%
    tab_style(style = cell_text(weight = "bold"), locations = cells_row_groups()) %>% 
    tab_style(style = cell_text(align = "right"), locations = cells_body(columns = "variable", rows = 15)) %>%
    fmt_markdown(columns = everything())
})

#extract HTML code of table
html_code <- list_gt %>% 
  map(as_raw_html) %>% 
  reduce(paste) 

#print in document
htmltools::browsable(htmltools::HTML(html_code))

```